site_name: Using Histograms
nav:
  - Introduction: index.md
  - Setup: 01_setup.md
  - Histogram Basics: 02_understanding_histograms.md
  - Plotting Examples: 03_plotting_data.md
  - Conclusion: 04_conclusion.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js