site_name: Using Histograms
nav:
  - Home: index.md
  - Introduction: 01_introduction.md
  - Setup: 02_setup.md
  - Histogram Basics: 03_understanding_histograms.md
  - Plotting Examples: 04_plotting_data.md
  - Conclusion: 05_conclusion.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js